# Generated by Django 3.2.17 on 2023-05-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prerec_for',
            field=models.ManyToManyField(related_name='course_prerec_for', to='document.Course'),
        ),
        migrations.AlterField(
            model_name='document',
            name='prerequisites',
            field=models.ManyToManyField(related_name='course_prerequisites', to='document.Course'),
        ),
    ]
