# Generated by Django 3.2.17 on 2023-05-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20230530_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='course_name',
            field=models.CharField(max_length=20),
        ),
    ]
