# Generated by Django 3.2.17 on 2023-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='learning_outcomes',
        ),
        migrations.AddField(
            model_name='document',
            name='learning_outcomes',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
