# Generated by Django 3.2.17 on 2023-05-29 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20230530_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='instructors',
        ),
        migrations.AddField(
            model_name='document',
            name='instructors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='document.instractor'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='document',
            name='prerec_for',
        ),
        migrations.AddField(
            model_name='document',
            name='prerec_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='course_prerec_for', to='document.course'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='document',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='document',
            name='prerequisites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='course_prerequisites', to='document.course'),
            preserve_default=False,
        ),
    ]
