# Generated by Django 3.2.17 on 2023-05-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_document_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='learning_outcomes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
