# Generated by Django 3.2.17 on 2023-05-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_alter_document_learning_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
