# Generated by Django 3.2.17 on 2023-05-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_document_learning_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='course_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
